### ISSUE TITLE
IInvoker and IDispatcher rename

### ISSUE THREAD

**Issue by JosephWoodward** [shaynevanasperen/Magneto#6]
Have you considered renaming the `IInvoker` and `IDispatcher` interfaces to something more Magneto specific, such as `IMagnetoInvoker` and `IMagnetoDispatcher`?

I'm wrestling internally with such a change but looking through the samples it comes across as very vague
and ambiguous type, plus there's an additional benefit (albeit minor) gained from increased memorability and awareness of the library (similar to the `IMediator` interface seen in alternatives such as MediatR).

cc @slang25

**Comment by stuart-lang** [comment]
Only just seen this issue. It's a good suggestion and worth considering 👍

**Comment by shaynevanasperen** [comment]
I'd like some suggestions for this, other than `IMagnetoInvoker` and `IMagnetoDispatcher` (because I think those names are a little too long and not catchy enough). I'm also thinking of combining those into one interface/implementation. I was thinking of calling it `IInvoke` so that your field would be named `_invoke` and usage would be nicely readable like:
```cs
var user = _invoke.Query(new UserById { Id = 1 });
```

Another idea is to call it `IConnector`. What do you think?

**Comment by JosephWoodward** [comment]
I agree (`IMagnetoInvoker`) is a little long, I couldn't think of anything shorter that has the name `Magneto` in it, which is what I feel should be added considering it's the main entry point API to the Magneto. What about `IMagneto.Invoke` and `IMagneto.Dispatch`?
